services:
  webhook-tower:
    image: ghcr.io/fkryakbar/webhook-tower:latest
    container_name: webhook-tower
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/config/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
